Updated potfiles script to work with multiple translation domains.
Reported by Jacob Nevins <jtn>

See bug #21543

[[originally from svn r26113]]

diff --git a/scripts/potfiles b/scripts/potfiles
--- a/scripts/potfiles
+++ b/scripts/potfiles
@@ -1,27 +1,27 @@
 #!/bin/bash
 
-POT1="po/POTFILES.in"
+domains="freeciv nations"
 
 if test "$1" == "" ; then 
-	echo Usage: $0 '<path to source root directory with trailing slash>'
-exit;
+  echo Usage: $0 '<path to source root directory with trailing slash>'
+  exit 1;
 fi
 
-POT2="$1"/$POT1
+for domain in $domains ; do
+  if ! test -f $1/translations/$domain/POTFILES.in ; then
+    echo "Cannot find $1/translations/$domain/POTFILES.in" >&2
+    exit 1
+  fi
+  POTLIST="$POTLIST $1/translations/$domain/POTFILES.in"
+done
 
-if test ! -f $POT2 ; then
-	echo cannot find $POT2 - abort ;
-	exit;
-fi
-
-sort < $POT2 > /tmp/potfile
+cat $POTLIST | grep -v "^#" | sed "s,^,$1," | sort > /tmp/potfile
 
 echo Suggestions for addition or removal of files with translatable strings to/from POTFILES.in:
 echo Please check the output manually
 
 find "$1" -name '*.c' -o -name '*.cpp' -o -name '*.h' -o -name '*.sav' -o -name '*.lua' -o -name '*.ruleset' -o -name '*.txt' -o -name '*.in' | 
   xargs grep -l -I '_("' |
-    sed "s%$1%%g" |
-      sort |
-        diff -u /tmp/potfile - |
-          egrep '^[+-]\w'
+    sort |
+      diff -u /tmp/potfile - |
+        egrep '^[+-]'
